# FILTRAR  FILAS

In [83]:
import pandas as pd
import seaborn as sns

In [84]:
# Load the Tips dataset
tips = sns.load_dataset("tips")

In [85]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

RESUMEN

Con corchetes filtramos o filas o col

iloc filas o columnas por posicion

loc por nombre y / o por condicion

1. FILTRADO POR RANGO DE VALORES

In [86]:
df[0:5]
# Aquí coge las 5 primeras filas por posiciones

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

2. FILTRADO POR NOMBRE DE LA COLUMNA --> "day" = coge la columna llamada day

In [87]:
df["day"]
# esto es una serie (tiene 1 corchete)

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

3. FILTRADO PONIENDO UNA LISTA DE NOMBRES DE COLUMNAS (ojo! 2 corchetes = lista de nombres)

In [88]:
df[["day"]]
# esto es un dataframe de una columna y permite mas de una columna

      day
0     Sun
1     Sun
2     Sun
3     Sun
4     Sun
..    ...
239   Sat
240   Sat
241   Sat
242   Sat
243  Thur

[244 rows x 1 columns]

In [89]:
df[["day", "tip"]]

      day   tip
0     Sun  1.01
1     Sun  1.66
2     Sun  3.50
3     Sun  3.31
4     Sun  3.61
..    ...   ...
239   Sat  5.92
240   Sat  2.00
241   Sat  2.00
242   Sat  1.75
243  Thur  3.00

[244 rows x 2 columns]

### ACCEDER A DATOS

1. ACCESO POR POSICION CON ILOC (poco usado) --> df.iloc [filas, columnas]

In [90]:
df.iloc [0,0] # filas, columnas
# accedo a valor de 1a fila y 1a columna

np.float64(16.99)

In [92]:
df.iloc [0:3,0:2]
# accedo a 3 primeras filas y 2 1as columnas

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50

2. ACCESO POR CONDICION CON .loc

2.1 ACCESO POR NOMBRE (TAMBIEN LLAMADO ACCESO POR ETIQUETA) (MAS COMUN QUE CON EL ILOC, PUES PUEDE CAMBIAR DE NOMBRE LA COLUMNA)

In [93]:
df.loc[0,"sex"]
# Accedo a la fila que se llama "0" y la columna llamada "sex"

'Female'

In [94]:
df.loc[[0,4,8],["sex","day"]]
# coge por nombres de columnas (sex, day) y nombres de filas (0,4,8)

      sex  day
0  Female  Sun
4  Female  Sun
8    Male  Sun

2.2 ACCESO POR CONDICIONES --> CONDICION DE FILAS , HABLO DE UNA COLUMNA Y SELECCIONA AQUELLAS FILAS DONDE LA CONDICION COLUMNA DE TIP SEA > 3

In [96]:
df.loc[df["tip"] > 3, ["smoker","time"]] #selecciona las filas con > 3 de propina y ensena solo las columnas smoker y time
df.loc[df["tip"] > 3, :] # me dara todas las filas con tip > 3 y todas las columnas

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
219       30.14  3.09  Female    Yes  Sat  Dinner     4
221       13.42  3.48  Female    Yes  Fri   Lunch     2
232       11.61  3.39    Male     No  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[98 rows x 7 columns]

2.2.1 ACCESO CON 2 CONDICIONES TIPO AND Y OR DE PYTHON ES CON & O |

In [101]:
df.loc[(df["tip"] > 3) & (df["tip"] < 5) , ["smoker","time"]]
df.head()
# 2 condiciones tip mayor que 3 y menor que 5 , no fumadores pero solo veo columnas smoker y time

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [100]:
df.loc[(df["tip"] > 3) | (df["tip"] < 5) , ["smoker","time"]]
df.head()

# la barra es como el or

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

2.2.3 ACCESO POR COLUMNAS (POCO HABITUAL)

In [103]:
df.loc[(df["tip"] > 3) & (df["tip"] < 5),[c for c in df.columns if "i" in c]]
df.head()
# selecciona las propinas entre 3 y 5 pero solo las columnas que contienen la letra "i"
# Usos en encuestas seleccionar los que tienen un codigo concreto o las columnas que por ejemplo tiene el icono $

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

NOTA IMP:
SI QUEREMOS QUE EL DIA ESTE EN UNA SERIE DE VALORES SE PONE COMO QUE ESOS VALORES ESTEN EN UNA LISTA DE DIAS (ademas aqui de poner condicion de que el nombre de la columna contenga la i)

In [105]:
df.loc[df["day"].isin(["Sun","Sat","Fri"]), [c for c in df.columns if "i" in c]]
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4