In [13]:
import pandas as pd
import seaborn as sns

-----

<span style="color: red;">Este texto aparece en rojo</span>

------

<div style="background-color: #E8F8F5; padding: 20px; border: 2px solid #1ABC9C; border-radius: 10px;">
    <strong>Celda destacada</strong><br>
    Aquí puedes escribir todo tu contenido.
</div>

<span style="background-color: #FFE4B5;">Texto con fondo color melocotón</span>

<div style="background-color: #FFF9C4; padding: 15px; border-left: 6px solid #FBC02D;">
    Nota importante: recuerda revisar los datos antes de ejecutar el modelo.
</div>

<div style="background-color: #FADBD8; padding: 20px;">
    Texto con fondo rojo suave ocupando toda la celda.
</div>

In [ ]:
df = sns.load_dataset("penguins")
df.head()


<div style="background-color: #FADBD8; padding: 30px;">
    GROUP BY.
</div>

----

### 1 VAR CATEGORICA

----

In [41]:
# NO IMP
# Agrupación básica por una variable categórica (especie).
# Ejecutar solo el groupby devuelve un objeto agrupador, no un resultado visual útil todavía. No util, lo util es para calcular las fcs de agregacion sum,min, count
df.groupby('species')

In [42]:
# NO ASI
# Para obtener resultados, se aplican funciones de agregación como sum (suma), mean (media) o count (recuento).

# Si se aplica directamente al dataframe, se intentará aplicar a todas las columnas.

# OJO CON LA SUM PQ TE SUMA EL TEXTO COMO TIPO CONCAT Y ADEMAS RECOMIENDA PONERLO ENTRE CORCHETES

df.groupby("species").sum()

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
species,,,,,,
Adelie,TorgersenTorgersenTorgersenTorgersenTorgersenT...,5857.5,2770.3,28683.0,558800.0,MaleFemaleFemaleFemaleMaleFemaleMaleFemaleMale...
Chinstrap,DreamDreamDreamDreamDreamDreamDreamDreamDreamD...,3320.7,1252.6,13316.0,253850.0,FemaleMaleMaleFemaleMaleFemaleFemaleMaleFemale...
Gentoo,BiscoeBiscoeBiscoeBiscoeBiscoeBiscoeBiscoeBisc...,5843.1,1842.8,26714.0,624350.0,FemaleMaleFemaleMaleMaleFemaleFemaleMaleFemale...

----

### 1 VARS NUMERICA: CALCULO DE FC AGG DE NUMERICA POR ESPECIE

----

In [44]:
# ASI
# calculo de la media de peso por especie
# Selección de una columna específica para el resumen (devuelve una Serie). mejor asi no sino q devuleva tipo df
df.groupby("species")[["body_mass_g"]].mean()

# Uso de doble corchete para obtener el resultado en formato DataFrame.
# Hace la media del body_mass_g por cada especie

           body_mass_g
species
Adelie     3700.662252
Chinstrap  3733.088235
Gentoo     5076.016260

----

### 2 VARS NUMERICAS: AGRUPACION POR 2 VAR NUM

----

In [46]:
# AGRUPACION POR 2 VARS NUMERICAS
# ASI SI LE PIDO 2 VARIABLES DE 2 COLUMNAS EJ LAS MEDIAS
# Agrupación por múltiples columnas numéricas (masa corporal y longitud de aleta).
# Es una agrupacion por 2 variables numericas.
df.groupby('species')[['body_mass_g', 'flipper_length_mm']].mean()

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

----

### AGRUPACION POR MAS DE 1 VAR CAT (species, sex)

----

In [20]:
# AHORA 2 VARIABLES CATEGORICAS (SPECIES Y SEX)
# Agrupación por múltiples variables categóricas (especie y sexo).
# Se puede hacer mean, count, sum (ojo con sum), describe (resumen estadistico)
df.groupby(['species', 'sex'])[['body_mass_g', 'flipper_length_mm']].mean()

                  body_mass_g  flipper_length_mm
species   sex
Adelie    Female  3368.835616         187.794521
          Male    4043.493151         192.410959
Chinstrap Female  3527.205882         191.735294
          Male    3938.970588         199.911765
Gentoo    Female  4679.741379         212.706897
          Male    5484.836066         221.540984

In [21]:
# Obtención de un resumen estadístico completo (media, desviación, cuartiles, etc.) usando .describe().
df.groupby('species')[['body_mass_g', 'flipper_length_mm']].describe()

          body_mass_g                                                   \
                count         mean         std     min     25%     50%
species
Adelie          151.0  3700.662252  458.566126  2850.0  3350.0  3700.0
Chinstrap        68.0  3733.088235  384.335081  2700.0  3487.5  3700.0
Gentoo          123.0  5076.016260  504.116237  3950.0  4700.0  5000.0

                          flipper_length_mm                               \
              75%     max             count        mean       std    min
species
Adelie     4000.0  4775.0             151.0  189.953642  6.539457  172.0
Chinstrap  3950.0  4800.0              68.0  195.823529  7.131894  178.0
Gentoo     5500.0  6300.0             123.0  217.186992  6.484976  203.0


             25%    50%    75%    max
species
Adelie     186.0  190.0  195.0  210.0
Chinstrap  191.0  196.0  201.0  212.0
Gentoo     212.0  216.0  221.0  231.0

## CON 2 FCS AGG DISTINTAS , EJ MEAN Y MIN

In [24]:
# Uso de .agg() (o .aggregate()) con un diccionario para aplicar funciones distintas a cada columna.
df.groupby(['species', 'sex'])[['body_mass_g','flipper_length_mm']].agg({
    'body_mass_g': 'mean',
    'flipper_length_mm': 'min'
})

                  body_mass_g  flipper_length_mm
species   sex
Adelie    Female  3368.835616              172.0
          Male    4043.493151              178.0
Chinstrap Female  3527.205882              178.0
          Male    3938.970588              187.0
Gentoo    Female  4679.741379              203.0
          Male    5484.836066              208.0

In [26]:
# Uso de .agg() (o .aggregate()) con un diccionario para aplicar funciones distintas a cada columna y sacar varias fcs de agregacion el min y el max
# Aplicación de múltiples funciones de resumen a una misma columna mediante una lista.
df.groupby(['species', 'sex'])[['body_mass_g','flipper_length_mm']].agg({
    'body_mass_g': 'mean',
    'flipper_length_mm': ['min','max']})

                  body_mass_g flipper_length_mm
                         mean               min    max
species   sex
Adelie    Female  3368.835616             172.0  202.0
          Male    4043.493151             178.0  210.0
Chinstrap Female  3527.205882             178.0  202.0
          Male    3938.970588             187.0  212.0
Gentoo    Female  4679.741379             203.0  222.0
          Male    5484.836066             208.0  231.0


<div style="background-color: #FADBD8; padding: 30px;">
    CROSSTAB.
</div>

In [29]:
# CROSSTAB  es una funcion no un metodo

# La función crosstab crea una matriz de frecuencias entre variables categóricas (filas species aqui y columnas sex aqui).
# si no especifico nada el crosstab hace un recuento pero puedo hacer otras agg
pd.crosstab(df['species'], df['sex'])

sex        Female  Male
species
Adelie         73    73
Chinstrap      34    34
Gentoo         58    61

### MARGENES

In [47]:

# Inclusión de márgenes para calcular los totales por filas y por columnas.
pd.crosstab(df['species'], df['sex'], margins=True)

sex        Female  Male  All
species
Adelie         73    73  146
Chinstrap      34    34   68
Gentoo         58    61  119
All           165   168  333

### NORMALIZACION

In [48]:
# Normalización de los datos para convertirlos en porcentajes sobre el total ya sea por filas como por columnas, es con el parametro normalize = all
pd.crosstab(df['species'], df['sex'], normalize='all')*100

sex           Female       Male
species
Adelie     21.921922  21.921922
Chinstrap  10.210210  10.210210
Gentoo     17.417417  18.318318

In [49]:
# Normalización por filas ('index') o por columnas ('columns'), útil para gráficos apilados.
pd.crosstab(df['species'], df['sex'], normalize='index')*100

# ESTO UTIL PARA HACER GRAFICOS APILADOS

sex           Female       Male
species
Adelie     50.000000  50.000000
Chinstrap  50.000000  50.000000
Gentoo     48.739496  51.260504

In [50]:
# Por columnas
pd.crosstab(df['species'], df['sex'], normalize='columns')*100

sex           Female       Male
species
Adelie     44.242424  43.452381
Chinstrap  20.606061  20.238095
Gentoo     35.151515  36.309524

In [51]:
# TODO
# HACER UNA FUNCION SOBRE EL BODY MASS ES CON AGGFUNC

# Uso de crosstab para calcular la media de una variable numérica (flipper_length_mm) en el cruce de categorías.
# Esto funciona de forma similar a una transposición o pivotado de datos.
pd.crosstab(
    index=df['species'],
    columns=df['sex'],
    values=df['flipper_length_mm'],
    aggfunc='mean'
)

sex            Female        Male
species
Adelie     187.794521  192.410959
Chinstrap  191.735294  199.911765
Gentoo     212.706897  221.540984


**Resumen de los conceptos clave aplicados en el script:**

RESUMEN DE VAR CAT POR VAR NUM
*   **Funciones de agregación:** Se utilizan para resumir los datos (suma, media, recuento, etc.) tras agruparlos.
*   **Formato de salida:** El uso de doble corchete asegura que el resultado se visualice como un DataFrame de Pandas en lugar de una serie.
*   **Flexibilidad con `.agg()`:** Permite personalizar qué estadística se calcula para cada columna específica.
*   **Tablas Cruzadas:** `crosstab` facilita la visualización de frecuencias y permite normalizar los datos para obtener porcentajes, lo que resulta fundamental para la creación de gráficos posteriores.