
<div style="background-color: #FADBD8; padding: 30px;">
    CREACION DE COLUMNAS.
</div>

<div style="background-color: #E8F8F5; padding: 20px; border: 2px solid #1ABC9C; border-radius: 10px;">
    <strong>Celda destacada</strong><br>
    Aquí puedes escribir todo tu contenido.
</div>

-----

<span style="color: red;">Este texto aparece en rojo</span>

------

<span style="background-color: #FFE4B5;">Texto con fondo color melocotón</span>

<div style="background-color: #FFF9C4; padding: 15px; border-left: 6px solid #FBC02D;">
    Nota importante: recuerda revisar los datos antes de ejecutar el modelo.
</div>


<div style="background-color: #FADBD8; padding: 30px;">
    CREACION DE COLUMNAS.
</div>

In [53]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [54]:
# 0. Creación del DataFrame inicial
# El video menciona un dataframe con nombres, edades y salarios.
df = pd.DataFrame({
    'ID': [1,2,3,4],
    'Nombre': ['Ana', 'Juan', 'Luis', 'Marta'],
    'Edad': [25,30,22,28],
    'Salario': [3200, 1500, 2800,1200]
})

df.head()

   ID Nombre  Edad  Salario
0   1    Ana    25     3200
1   2   Juan    30     1500
2   3   Luis    22     2800
3   4  Marta    28     1200

---
### AÑADIR UNA COLUMNA QUE SEA UNA CTE
---

In [55]:
# 1. Añadir una columna constante - POCO UTIL salvo para crear una columna que tenga un valor y luego hacer algo con ella
df['País'] = 'España'
df

   ID Nombre  Edad  Salario    País
0   1    Ana    25     3200  España
1   2   Juan    30     1500  España
2   3   Luis    22     2800  España
3   4  Marta    28     1200  España

---
### HACER 1 OPERACION SOBRE UNA COLUMNA
---

In [56]:
# 2. Operación sobre una columna (Salario anual)
# Se recomienda no usar espacios en los nombres de las columnas para facilitar el acceso con punto.
df['Salario_Anual'] = df['Salario'] * 12
df

   ID Nombre  Edad  Salario    País  Salario_Anual
0   1    Ana    25     3200  España          38400
1   2   Juan    30     1500  España          18000
2   3   Luis    22     2800  España          33600
3   4  Marta    28     1200  España          14400

---
### CREAR UNA COLUMNA POR CONDICION
---

In [57]:
# NO GUSTA MEJOR CON .LOC
# 3. Condicional simple con np.where
# Si la edad es <= 25 es 'muy joven', de lo contrario 'adulto joven'.
df['grupo_edad'] = np.where(df['Edad'] <= 25, 'muy joven', 'adulto joven')
df

   ID Nombre  Edad  Salario    País  Salario_Anual    grupo_edad
0   1    Ana    25     3200  España          38400     muy joven
1   2   Juan    30     1500  España          18000  adulto joven
2   3   Luis    22     2800  España          33600     muy joven
3   4  Marta    28     1200  España          14400  adulto joven

---
### CREAR UNA COLUMNA POR CONDICION FELXIBLE USANDO .LOC
---

In [58]:
# 4. Condicionales flexibles usando .loc
# Permite asignar valores basados en condiciones específicas, la columna de status_economico al no existir la cre, MUY UTIL

df.loc[df['Salario'] > 2000, 'Edad'] # me dara la edad de las personas con salario > 2000

# SI LE PIDO UNA COLUMNA QUE NO EXISTE ENTONCES LA CREARA POR EJ STATUS ECONOMICO Y  SI LE ASIGNO UN VALOR (RICO) Y A ESTA COLUMNA SE LE DARA EL VALOR RICO CUANDO SALARIO SEA  2000
df.loc[df['Salario'] > 2000, 'status_economico'] = 'rico'
df.loc[df['Salario'] <= 2000, 'status_economico'] = 'no tan rico'
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico
0,1,Ana,25,3200,España,38400,muy joven,rico
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico
2,3,Luis,22,2800,España,33600,muy joven,rico
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico

---
### APLICAR FC A 1 COL
---

In [59]:
# 5. Aplicar una función con lambda (Mayúsculas)
# Se usa .apply para transformar cada valor de la columna nombre a mayúsculas.
df['nombre_mayusculas'] = df['Nombre'].apply(lambda x: x.upper())

# es lo mismo que poner toda la fc
def mayuscula(x):
    return x.upper()
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA

In [60]:

# 6. Aplicar una función definida explícitamente (Tramos de impuestos)
def salario_neto(salario):
    if salario < 1100:
        return salario
    elif 1100 <= salario < 1800:
        return salario * 0.9  # 10% impuesto
    elif 1800 <= salario < 2500:
        return salario * 0.8  # 20% impuesto
    else:
        return salario * 0.7  # 30% impuesto

df['Salario_Neto'] = df['Salario'].apply(salario_neto)
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Salario_Neto
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,2240.0
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,1350.0
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,1960.0
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,1080.0

<div style="background-color: #FFF9C4; padding: 15px; border-left: 6px solid #FBC02D;">
    Nota importante.
</div>

In [61]:
# BORRAR COL
del df["Salario_Neto"]

---
### AÑADIR VALORES ALEATORIOS
---

In [62]:
# 7. Añadir valores aleatorios
# Genera 4 números aleatorios entre 50 y 99 según la cantidad de filas.
df['Puntos'] = np.random.randint(50, 100, size=len(df))
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Puntos
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,91
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,62
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,52
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,68

---
### GUARDAR EL INDICE COMO UNA COLUMNA
---

In [63]:
# 8. Guardar el índice como una columna
# Útil para mantener la trazabilidad si se reordena el dataframe.
df['indice_original'] = df.index
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Puntos,indice_original
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,91,0
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,62,1
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,52,2
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,68,3

---
### AÑADIR UNA COLUMNA NUEVA A PARTIR DE LOS VALORES DE UNA LISTA
---

In [64]:
# 9. Añadir columna a partir de una lista
df['Grupo'] = ['A', 'B', 'C', 'D']
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Puntos,indice_original,Grupo
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,91,0,A
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,62,1,B
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,52,2,C
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,68,3,D

---
### CREAR COLUMNA VACIA Y LLENARLA
---

In [65]:
# 10. Crear columna vacía y llenarla
df['vacio'] = np.nan
# Llenamos los nulos con 500
df['vacio'] = df['vacio'].fillna(500, inplace = True)
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Puntos,indice_original,Grupo,vacio
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,91,0,A,500.0
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,62,1,B,500.0
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,52,2,C,500.0
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,68,3,D,500.0

In [66]:
# si quiero que aparezca como int añadiria

df['vacio'] = df['vacio'].astype("i")
df

,ID,Nombre,Edad,Salario,País,Salario_Anual,grupo_edad,status_economico,nombre_mayusculas,Puntos,indice_original,Grupo,vacio
0,1,Ana,25,3200,España,38400,muy joven,rico,ANA,91,0,A,500
1,2,Juan,30,1500,España,18000,adulto joven,no tan rico,JUAN,62,1,B,500
2,3,Luis,22,2800,España,33600,muy joven,rico,LUIS,52,2,C,500
3,4,Marta,28,1200,España,14400,adulto joven,no tan rico,MARTA,68,3,D,500

---
### CREAR UN RANKING
---

In [68]:
# 11. Crear un ranking
# Ranking descendente basado en el salario.
df['Salario_Ranking'] = df['Salario'].rank(ascending=False).astype("i")
df

# Mostrar el resultado final
print(df)

   ID Nombre  Edad  Salario    País  Salario_Anual    grupo_edad  \
0   1    Ana    25     3200  España          38400     muy joven
1   2   Juan    30     1500  España          18000  adulto joven
2   3   Luis    22     2800  España          33600     muy joven
3   4  Marta    28     1200  España          14400  adulto joven

  status_economico nombre_mayusculas  Puntos  indice_original Grupo  vacio  \
0             rico               ANA      91                0     A    500
1      no tan rico              JUAN      62                1     B    500
2             rico              LUIS      52                2     C    500
3      no tan rico             MARTA      68                3     D    500

   Salario_Ranking
0                1
1                3
2                2
3                4



### Notas adicionales basadas en las fuentes:
*   **Acceso a columnas:** El autor recomienda **no poner espacios** en los nombres de las columnas para poder acceder a ellas usando la notación de punto (ej. `df.nombre`).
*   **Uso de .loc:** Es preferible sobre `np.where` cuando se necesitan manejar múltiples condiciones de manera estructurada.
*   **Persistencia de cambios:** Al usar métodos como `fillna`, recuerda que no se guardan automáticamente a menos que asignes el resultado de nuevo a la columna o uses el parámetro `inplace=True` (aunque este último no siempre está disponible en todos los métodos o versiones).