-----

<span style="color: red;">Este texto aparece en rojo</span>

------

<div style="background-color: #E8F8F5; padding: 20px; border: 2px solid #1ABC9C; border-radius: 10px;">
    <strong>Celda destacada</strong><br>
    Aquí puedes escribir todo tu contenido.
</div>

<span style="background-color: #FFE4B5;">Texto con fondo color melocotón</span>

<div style="background-color: #FFF9C4; padding: 15px; border-left: 6px solid #FBC02D;">
    Nota importante: recuerda revisar los datos antes de ejecutar el modelo.
</div>

<div style="background-color: #FADBD8; padding: 20px;">
    Texto con fondo rojo suave ocupando toda la celda.
</div>

<div style="background-color: #FADBD8; padding: 20px;">
    MERGE Y CONC
</div>

In [38]:
import pandas as pd
import numpy as np

In [39]:

# 1. Preparación de los datos

df1 = pd.DataFrame({'ID': [1,2,3], 'Nombre': ['Ana', 'Juan', 'Luis']})
df2 = pd.DataFrame({'ID': [3,4 ,5], 'Edad': [25,30,22]})
df3 = pd.DataFrame({'User_ID': [3,4 ,5], 'Edad': [25,30,22]})
df4 = pd.DataFrame({'ID': [1,2,3,3], 'Ciudad': ['Madrid', 'Barcelona', 'Sevilla','Valencia']})
df5 = pd.DataFrame({'Edad': [25,30,22]}, index = [1,2,3])
df6 = pd.DataFrame({'ID': [1,2,3], 'Nombre': ['Carlos', 'Pedro', 'Maria']})
df7 = pd.DataFrame({'ID': [1,2,3,3], 'Edad': [25,30,22,40]})

Merge : Mediante nexo / Concat : sin valor de nexo

In [40]:
df1

   ID Nombre
0   1    Ana
1   2   Juan
2   3   Luis

In [41]:
df2

   ID  Edad
0   3    25
1   4    30
2   5    22

In [42]:
# INNER mantiene SOLO las coincidencias
pd.merge(df1,df2, on = 'ID', how = 'inner')

   ID Nombre  Edad
0   3   Luis    25

In [43]:
# OUTER: mantiene toda la información de ambas tablas, rellenando con vacíos (NaN) donde no hay encaje.
pd.merge(df1,df2, on = 'ID', how = 'outer')

   ID Nombre  Edad
0   1    Ana   NaN
1   2   Juan   NaN
2   3   Luis  25.0
3   4    NaN  30.0
4   5    NaN  22.0

In [44]:
#LEFT: mantiene la tabla de la izquierda intacta y añade lo que pueda de la derecha.

left_result = pd.merge(df1, df2, on='ID', how='left')

In [45]:
# NO RECOMIENDA
# Right Join (Se recomienda mejor cambiar el orden de las tablas y usar left)
right_result = pd.merge(df1, df2, on='ID', how='right')

---
### MERGE NOMBRES DE COLUMNA O INDICES DISTINTOS
----

In [46]:
#Si las columnas de nexo se llaman distinto, usamos `left_on` y `right_on`. También se puede unir usando el índice de la fila con `right_index` o `left_index`.

# Diferentes nombres de columna
pd.merge(df1, df3, left_on='ID', right_on='User_ID')

   ID Nombre  User_ID  Edad
0   3   Luis        3    25

---
### UNIONES CON DIFERENTES NOMBRES DE COLUMNA O INDICES
---

In [47]:
### Uniones con diferentes nombres de columna o índices

# Unir usando el índice de la derecha
pd.merge(df1, df5, left_on = 'ID', right_index=True)

   ID Nombre  Edad
0   1    Ana    25
1   2   Juan    30
2   3   Luis    22

---
### MERGE CON SUFIJOS
---

In [48]:
### Parámetros avanzados: Sufijos e Indicador
# Podemos personalizar los sufijos cuando hay columnas duplicadas y usar `indicator` para saber de qué tabla proviene cada registro.

# Uso de sufijos personalizados
pd.merge(df1, df6, on='ID', suffixes=('_izq', '_der'))

   ID Nombre_izq Nombre_der
0   1        Ana     Carlos
1   2       Juan      Pedro
2   3       Luis      Maria

---
### MERGE CON INDICADOR DE ORIGEN (indicator)


---

In [49]:
# Indicador de origen (útil en outer joins para trazabilidad)
pd.merge(df1, df2, on = 'ID' ,how='outer', indicator=True)

   ID Nombre  Edad      _merge
0   1    Ana   NaN   left_only
1   2   Juan   NaN   left_only
2   3   Luis  25.0        both
3   4    NaN  30.0  right_only
4   5    NaN  22.0  right_only

---
#### indice MULTIPLE
---

In [51]:
#df1.merge(df2,on = ['Ciudad', 'Año'], how = 'inner')

---
### CONCAT
---

In [52]:
## 3. Operación Concat
# concat` se utiliza para **pegar tablas** directamente (ya sea por filas o columnas) sin buscar necesariamente una correspondencia entre valores.

#Concatenar por filas (axis=0) y columnas (axis=1)
#Por defecto, concatena por filas (`axis=0`). Si se desea pegar una al lado de la otra, se usa `axis=1`.


# Concatenar por filas
# Se pasa una lista de DataFrames
pd.concat([df1, df2], axis=0)

In [ ]:
pd.concat([df1, df2], axis=0)

---
### CONCATENAR POR COLUMNAS
---

In [57]:
# Concatenar por columnas
pd.concat([df1, df2], axis=1)

   ID Nombre  ID  Edad
0   1    Ana   3    25
1   2   Juan   4    30
2   3   Luis   5    22

---
### INDICES DESALINEADOS
---

In [58]:
### Manejo de índices en Concat
# Para evitar índices repetidos, se usa `ignore_index=True`. También se pueden crear índices múltiples (MultiIndex) para identificar el origen de los datos con `keys`.

# Resetear índices al unir
pd.concat([df1, df2], ignore_index=True)

   ID Nombre  Edad
0   1    Ana   NaN
1   2   Juan   NaN
2   3   Luis   NaN
3   3    NaN  25.0
4   4    NaN  30.0
5   5    NaN  22.0

---
### MULTIINDEX
---

In [60]:

# Crear MultiIndex para trazabilidad
pd.concat([df1, df2], keys=['Grupo 1', 'Grupo 2'])

           ID Nombre  Edad
Grupo 1 0   1    Ana   NaN
        1   2   Juan   NaN
        2   3   Luis   NaN
Grupo 2 0   3    NaN  25.0
        1   4    NaN  30.0
        2   5    NaN  22.0