# Level 1

#### Exercici 1

- Importa com un DataFrame l'arxiu sprint10.xlsx. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.
- Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.
- Mostra les primeres 10 files.

Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [155]:
#  Importar librerias

import numpy as np
import pandas as pd

In [156]:

# 1. Ajustar ruta del excel
ruta_datos = '/Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/03_Especialitzacio/Sprint_10_Analitica_dades_Python/Datos originales/sprint10.xlsx'

# Cargar el dataframe...(df) (Importar), la hoja Sheet1 y convierto indice del excel en indice del Dataframe (evito duplicar)
treballadors_2025 = pd.read_excel(ruta_datos, sheet_name="Sheet1", header=3, index_col=0) 

# 2. Ordeno el df por país y ciudad con sort_values que primero ordena por columna1 y despues por columna2
#  reseteo el indice sobre df y con drop evito me cree columna 
treballadors_2025 = treballadors_2025.sort_values(by=["País d'origen", "Ciutat"]).reset_index(drop=True)

# 3. Muestro con head las 10 primereas filas
treballadors_2025.head(10)

# 4. Con is_unique compruebo dinamicamente que el df no tiene DNI duplicados (True) 
# o si tiene DNI duplicados, print con resultado

if treballadors_2025['DNI'].is_unique:
    print("No existen DNI duplicados en el dataframe treballadors_2025")

else: 
    print("Existen DNI duplicados en el dataframe treballadors_2025")

No existen DNI duplicados en el dataframe treballadors_2025

#### Exercici 2

- Crea una columna que sigui el nom complet.
- Crea una columna si la persona és nascuda a Espanya o no.
- Posa el DNI com a índex del DataFrame (noms de files).
- Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
- Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
- Mostra tots els canvis que has realitzat en una sola taula.

In [157]:
# 1. - Crea una columna que sigui el nom complet.
# Nombre completo con concat

treballadors_2025['Nom Complet'] = treballadors_2025['Nom'] + ' ' + treballadors_2025['Cognoms']

treballadors_2025

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet
0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer
1,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer
2,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider
3,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer
4,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones
996,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones
997,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown
998,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown
999,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith

In [158]:
# 2. - Crea una columna si la persona és nascuda a Espanya o no.

treballadors_2025['Nascut_Espanya'] = np.where(treballadors_2025["País d'origen"] == 'Espanya', 'Si', 'No')
treballadors_2025.head(100)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet,Nascut_Espanya
0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
1,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
2,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
3,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
4,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Oriol,Sánchez,40695825B,Espanya,Barcelona,27,7,1965,H,1.250 €,NaN,1.0,Grup A,Oriol Sánchez,Si
96,Toni,Castells Romero,74222289K,Espanya,Barcelona,13,4,1961,H,1.438 €,NaN,1.0,Grup B,Toni Castells Romero,Si
97,Núria,Castells,13107162J,Espanya,Barcelona,2,7,2005,D,1.344 €,1.0,NaN,Grup A,Núria Castells,Si
98,Toni,Castells Martínez,29801291B,Espanya,Barcelona,10,1,1981,H,2.102 €,1.0,NaN,Grup B,Toni Castells Martínez,Si
99,Oriol,López Martínez,89977538X,Espanya,Barcelona,25,6,1952,H,1.019 €,1.0,NaN,Grup A,Oriol López Martínez,Si

In [159]:
treballadors_2025.describe()

       Dia de Naixement  Mes de Naixement  Any de Naixement  Fills  No Fills
count       1000.000000       1000.000000       1000.000000  406.0     594.0
mean          14.758000          6.440000       1976.425000    1.0       1.0
std            8.115127          3.444164         16.134643    0.0       0.0
min            1.000000          1.000000       1950.000000    1.0       1.0
25%            8.000000          3.000000       1962.000000    1.0       1.0
50%           15.000000          6.000000       1976.000000    1.0       1.0
75%           22.000000          9.000000       1990.000000    1.0       1.0
max           28.000000         12.000000       2005.000000    1.0       1.0

In [160]:
# 3. - Posa el DNI com a índex del DataFrame (noms de files).
# Con set_index() indico la columna que quiero asignar como indice del df, tambien podría usar inplace=True para machacar el propio df
# treballadors_2025.set_index('DNI', inplace=True)

treballadors_2025 = treballadors_2025.set_index('DNI')
treballadors_2025

,Nom,Cognoms,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet,Nascut_Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones,No
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith,No

In [161]:
# 4. - Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
# Uso metodo rename junto al diccionario de nombre columnas antes:despues

treballadors_2025 = treballadors_2025.rename(columns={"Dia de Naixement": "Dia", "Mes de Naixement": "Mes", "Any de Naixement": "Any"})
print(treballadors_2025.columns)

Index(['Nom', 'Cognoms', 'País d'origen', 'Ciutat', 'Dia', 'Mes', 'Any',
       'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional',
       'Nom Complet', 'Nascut_Espanya'],
      dtype='str')

In [162]:
# 5. - Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
# el metode replace() permet canviar un valor per un altre, en aquest cas com que eren varis he fet servir un diccionari
#  uso np.nan ya que es el objeto nulo de python es un valor especial de ausencia de datos

treballadors_2025['Gènere'] = treballadors_2025['Gènere'].replace({
    'H': 'Home',
    'D': 'Dona',
    'A': 'Altres',
    'NC': np.nan
})

treballadors_2025.tail(100)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom Complet,Nascut_Espanya
DNI,,,,,,,,,,,,,,
60378955C,Fatima,Zahraoui El Amrani,Marroc,Rabat,27,1,1986,Dona,1.312 €,NaN,1.0,Grup A,Fatima Zahraoui El Amrani,No
53822006D,Ali,El Amrani El Amrani,Marroc,Rabat,4,5,1971,Home,2.127 €,NaN,1.0,Grup B,Ali El Amrani El Amrani,No
13257049V,Youssef,Fassi Zahraoui,Marroc,Rabat,13,7,1974,Altres,1.109 €,1.0,NaN,Grup A,Youssef Fassi Zahraoui,No
78697534Q,Omar,Zahraoui Zahraoui,Marroc,Rabat,1,7,1983,NaN,1.271 €,1.0,NaN,Grup A,Omar Zahraoui Zahraoui,No
77665617B,Youssef,Bennani El Amrani,Marroc,Rabat,5,9,1960,Home,1.619 €,NaN,1.0,Grup A,Youssef Bennani El Amrani,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,1.0,NaN,Grup A,George Brown Jones,No
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,NaN,1.0,Grup A,Isla Jones Brown,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,1.0,NaN,Grup A,William Smith,No

In [163]:
# 6- Mostra tots els canvis que has realitzat en una sola taula.

cambios = treballadors_2025[['Nom Complet', 'Nascut_Espanya', 'Dia', 'Mes', 'Any', 'Gènere']]
cambios

                       Nom Complet Nascut_Espanya  Dia  Mes   Any  Gènere
DNI
28973553Z    Mia Schneider Fischer             No   22   10  1976  Altres
37399141L  Laura Schneider Fischer             No    2    2  1958    Dona
37368317L  Lea Schneider Schneider             No   23   10  2005    Dona
21390098Z              Mia Fischer             No   11    8  1950    Dona
44060014R          Jonas Schneider             No   22   11  1985    Home
...                            ...            ...  ...  ...   ...     ...
89577876S       Emily Taylor Jones             No   28    3  1958    Dona
57441590Y       George Brown Jones             No   27   12  1979    Home
58204038A       Olivia Brown Brown             No   28    8  1952  Altres
28367234K         Isla Jones Brown             No   28    3  1999    Dona
82046699J            William Smith             No   19    5  1997    Home

[1000 rows x 6 columns]

#### Exercici 3

Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

- Para solucionar problema planteo que si tiene Fills = 1 obliga a "No Fills" = 0  y viceversa, 
así que en la funcion solo tengo que averiguar si Fills = 1 
- con la respuesta de la funcion 'tiene_hijos' lleno la columna Fills y despues elimino con Drop la 'No Fills'

In [164]:
def tiene_hijos(fill):
    if fill == 1:
        return "Sí"
    else:
        return "No"
    
treballadors_2025['Fills'] = treballadors_2025['Fills'].apply(tiene_hijos)
treballadors_2025 = treballadors_2025.drop(['No Fills'], axis=1)

treballadors_2025

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom Complet,Nascut_Espanya
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,Grup A,Mia Schneider Fischer,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,Grup B,Laura Schneider Fischer,No
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,Grup B,Lea Schneider Schneider,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,Grup B,Mia Fischer,No
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,Grup D,Jonas Schneider,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,Grup B,Emily Taylor Jones,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,Grup A,George Brown Jones,No
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,Grup A,Olivia Brown Brown,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,Grup A,Isla Jones Brown,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,Grup A,William Smith,No

#### Exercici 4

- Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.
- Ordena la taula en funció del sou mig.

- Afrontaré este reto con un Group by Gènere y luego con una agregacion multiple finalmente el Order By Sueldo Medio
- Reto encontrado es que 'Salari mensual' viene como string y hay que transformar a int

In [165]:
treballadors_2025['Salari mensual'] = (treballadors_2025['Salari mensual']
                                    .str.replace(".","", regex=False)
                                    .str.replace("€","", regex=False)
                                    .str.replace(" ","", regex=False)
                                    .astype(int))

resum = (treballadors_2025.groupby(['Gènere'])['Salari mensual']
         .agg(['mean', 'median', 'min', 'max'])
         .sort_values('mean', ascending=False)
         .round(2)
         )
resum

           mean  median  min   max
Gènere
Home    1643.25  1531.0  737  3356
Altres  1626.59  1545.0  703  3175
Dona    1469.44  1361.5  665  3021

#### Exercici 5

- Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).
- Afegeix-hi les mitjanes als marges de la taula.
- (EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [166]:
treballadors_2025.info()

<class 'pandas.DataFrame'>
Index: 1000 entries, 28973553Z to 82046699J
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nom                1000 non-null   str
 1   Cognoms            1000 non-null   str
 2   País d'origen      1000 non-null   str
 3   Ciutat             1000 non-null   str
 4   Dia                1000 non-null   int64
 5   Mes                1000 non-null   int64
 6   Any                1000 non-null   int64
 7   Gènere             940 non-null    str
 8   Salari mensual     1000 non-null   int64
 9   Fills              1000 non-null   str
 10  Grup Professional  1000 non-null   str
 11  Nom Complet        1000 non-null   str
 12  Nascut_Espanya     1000 non-null   str
dtypes: int64(4), str(9)
memory usage: 179.1 KB

In [177]:
resum = pd.crosstab(treballadors_2025["Gènere"], 
            treballadors_2025["País d'origen"], 
            values= treballadors_2025["Salari mensual"], 
            aggfunc='mean',
            margins=True, margins_name="Total").round(2)

resum.style.apply(lambda x: ['background-color: yellow' if v == x.max() else '' for v in x]).format('{:.2f}')