# Pandas

Paquete analítica de datas fundamental de Python

In [ ]:
import pandas as pd

In [5]:
df = pd.read_csv("/Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/03_Especialitzacio/Sprint_9_Python/Apuntes/Python Intro 2024 Youtube/flights14.csv", index_col=0)
df

,year,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour
1,2014,1,1,14,13,AA,JFK,LAX,359,2475,9
2,2014,1,1,-3,13,AA,JFK,LAX,363,2475,11
3,2014,1,1,2,9,AA,JFK,LAX,351,2475,19
4,2014,1,1,-8,-26,AA,LGA,PBI,157,1035,7
5,2014,1,1,2,1,AA,JFK,LAX,350,2475,13
...,...,...,...,...,...,...,...,...,...,...,...
253312,2014,10,31,1,-30,UA,LGA,IAH,201,1416,14
253313,2014,10,31,-5,-14,UA,EWR,IAH,189,1400,8
253314,2014,10,31,-8,16,MQ,LGA,RDU,83,431,11
253315,2014,10,31,-4,15,MQ,LGA,DTW,75,502,11
253316,2014,10,31,-5,1,MQ,LGA,SDF,110,659,8

In [6]:
df.head()

,year,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour
1,2014,1,1,14,13,AA,JFK,LAX,359,2475,9
2,2014,1,1,-3,13,AA,JFK,LAX,363,2475,11
3,2014,1,1,2,9,AA,JFK,LAX,351,2475,19
4,2014,1,1,-8,-26,AA,LGA,PBI,157,1035,7
5,2014,1,1,2,1,AA,JFK,LAX,350,2475,13

In [7]:
df.tail()

,year,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour
253312,2014,10,31,1,-30,UA,LGA,IAH,201,1416,14
253313,2014,10,31,-5,-14,UA,EWR,IAH,189,1400,8
253314,2014,10,31,-8,16,MQ,LGA,RDU,83,431,11
253315,2014,10,31,-4,15,MQ,LGA,DTW,75,502,11
253316,2014,10,31,-5,1,MQ,LGA,SDF,110,659,8

In [8]:
df.describe()

,year,month,day,dep_delay,arr_delay,air_time,distance,hour
count,253316.0,253316.000000,253316.000000,253316.000000,253316.000000,253316.000000,253316.000000,253316.000000
mean,2014.0,5.638578,15.893698,12.465265,8.146702,156.722824,1099.445274,13.063435
std,0.0,2.820866,8.763097,41.648763,45.749452,96.129776,752.982282,4.897891
min,2014.0,1.000000,1.000000,-112.000000,-112.000000,20.000000,80.000000,0.000000
25%,2014.0,3.000000,8.000000,-5.000000,-15.000000,86.000000,533.000000,9.000000
50%,2014.0,6.000000,16.000000,-1.000000,-4.000000,134.000000,944.000000,13.000000
75%,2014.0,8.000000,23.000000,11.000000,15.000000,199.000000,1416.000000,17.000000
max,2014.0,10.000000,31.000000,1498.000000,1494.000000,706.000000,4983.000000,24.000000

In [9]:
df.describe(include = "object")

/var/folders/6f/lhr87vh51bq38sm9v46389m00000gn/T/ipykernel_18660/3591357663.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object")

       carrier  origin    dest
count   253316  253316  253316
unique      14       3     109
top         UA     EWR     LAX
freq     46267   87400   14434

In [10]:
del df["year"]

In [13]:
df["nueva columna"] = "hola"
df

,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour,nueva columna
1,1,1,14,13,AA,JFK,LAX,359,2475,9,hola
2,1,1,-3,13,AA,JFK,LAX,363,2475,11,hola
3,1,1,2,9,AA,JFK,LAX,351,2475,19,hola
4,1,1,-8,-26,AA,LGA,PBI,157,1035,7,hola
5,1,1,2,1,AA,JFK,LAX,350,2475,13,hola
...,...,...,...,...,...,...,...,...,...,...,...
253312,10,31,1,-30,UA,LGA,IAH,201,1416,14,hola
253313,10,31,-5,-14,UA,EWR,IAH,189,1400,8,hola
253314,10,31,-8,16,MQ,LGA,RDU,83,431,11,hola
253315,10,31,-4,15,MQ,LGA,DTW,75,502,11,hola
253316,10,31,-5,1,MQ,LGA,SDF,110,659,8,hola

In [14]:
df["velocidad"] = df["distance"] / df["air_time"]
df

,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour,nueva columna,velocidad
1,1,1,14,13,AA,JFK,LAX,359,2475,9,hola,6.894150
2,1,1,-3,13,AA,JFK,LAX,363,2475,11,hola,6.818182
3,1,1,2,9,AA,JFK,LAX,351,2475,19,hola,7.051282
4,1,1,-8,-26,AA,LGA,PBI,157,1035,7,hola,6.592357
5,1,1,2,1,AA,JFK,LAX,350,2475,13,hola,7.071429
...,...,...,...,...,...,...,...,...,...,...,...,...
253312,10,31,1,-30,UA,LGA,IAH,201,1416,14,hola,7.044776
253313,10,31,-5,-14,UA,EWR,IAH,189,1400,8,hola,7.407407
253314,10,31,-8,16,MQ,LGA,RDU,83,431,11,hola,5.192771
253315,10,31,-4,15,MQ,LGA,DTW,75,502,11,hola,6.693333
253316,10,31,-5,1,MQ,LGA,SDF,110,659,8,hola,5.990909

# Seleccionar informacion

In [20]:
df["air_time"]

1         359
2         363
3         351
4         157
5         350
         ...
253312    201
253313    189
253314     83
253315     75
253316    110
Name: air_time, Length: 253316, dtype: int64

In [18]:
df[["air_time", "distance"]]

        air_time  distance
1            359      2475
2            363      2475
3            351      2475
4            157      1035
5            350      2475
...          ...       ...
253312       201      1416
253313       189      1400
253314        83       431
253315        75       502
253316       110       659

[253316 rows x 2 columns]

In [21]:
df[0:5]

,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour,nueva columna,velocidad
1,1,1,14,13,AA,JFK,LAX,359,2475,9,hola,6.894150
2,1,1,-3,13,AA,JFK,LAX,363,2475,11,hola,6.818182
3,1,1,2,9,AA,JFK,LAX,351,2475,19,hola,7.051282
4,1,1,-8,-26,AA,LGA,PBI,157,1035,7,hola,6.592357
5,1,1,2,1,AA,JFK,LAX,350,2475,13,hola,7.071429

In [ ]:
# por posicion (tanto filas como columnas)

In [23]:
df.iloc[3,2]

np.int64(-8)

In [25]:
df.iloc[0:5,0:5]

   month  day  dep_delay  arr_delay carrier
1      1    1         14         13      AA
2      1    1         -3         13      AA
3      1    1          2          9      AA
4      1    1         -8        -26      AA
5      1    1          2          1      AA

In [ ]:
# por valor

In [ ]:
df.loc[1:5,["air_time","origin"]] # seleccionar por nombre

   air_time origin
1       359    JFK
2       363    JFK
3       351    JFK
4       157    LGA
5       350    JFK

In [30]:
df.loc[(df["air_time"] > 240) & (df["arr_delay"] > 30), ["origin", "dest"]] # origenes y destinos de vuelos de mas de 4 horas 
# para mas de una condicion usamos & pero tambien | = or. Parentesisi obligatorio entre las condiciones

       origin dest
14        JFK  LAX
116       JFK  LAS
120       JFK  LAS
129       JFK  SAN
151       JFK  LAS
...       ...  ...
253052    EWR  SFO
253054    JFK  SFO
253228    JFK  LAX
253285    EWR  SEA
253292    EWR  SFO

[7103 rows x 2 columns]

In [ ]:
# tiempo medio de vuelo de los que salen d JFK
df.loc[df["origin"] == "JFK", "air_time"].mean()

np.float64(195.27764073487722)