In [13]:
# =========================================================
# IMPORTS
# =========================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [14]:
# =========================================================
# DATA PATHS
# =========================================================

WIND_PATH = "../data/processed/badalona_wind_target.parquet"

BUOY_PATH = "../data/processed/barcelona_buoy_processed.parquet"

XEMA_PATH = "../data/gold/xema_hourly_model_ready.parquet"

In [15]:
# =========================================================
# LOAD DATASETS
# =========================================================

df_wind = pd.read_parquet(WIND_PATH)

df_buoy = pd.read_parquet(BUOY_PATH)

df_xema = pd.read_parquet(XEMA_PATH)

print("Datasets cargados correctamente")

Datasets cargados correctamente

In [17]:
# =========================================================
# QUICK DATASET INSPECTION
# =========================================================

datasets = {
    "WIND": df_wind,
    "BUOY": df_buoy,
    "XEMA": df_xema
}

for name, df_ in datasets.items():

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print(f"Shape: {df_.shape}")

    print("\nColumns:")
    print(df_.columns.tolist())

    print("\nDtypes:")
    print(df_.dtypes)

    print("\nFirst rows:")
    display(df_.head(3))

============================================================
WIND
============================================================
Shape: (298674, 17)

Columns:
['datetime', 'spot', 'temperature', 'wind_direction_deg', 'wind_avg', 'wind_min', 'wind_max', 'unknown', 'source_file', 'year', 'month', 'day', 'hour', 'weekday', 'season', 'wind_regime', 'is_sea_breeze']

Dtypes:
datetime              datetime64[us]
spot                             str
temperature                    int64
wind_direction_deg             int64
wind_avg                       int64
wind_min                       int64
wind_max                       int64
unknown                        int64
source_file                      str
year                           int32
month                          int32
day                            int32
hour                           int32
weekday                          str
season                           str
wind_regime                 category
is_sea_breeze                   int8
dtype: object

First rows:

,datetime,spot,temperature,wind_direction_deg,wind_avg,wind_min,wind_max,unknown,source_file,year,month,day,hour,weekday,season,wind_regime,is_sea_breeze
0,2010-01-01 08:00:07,BDLONA,10,267,11,4,19,1,100101.log,2010,1,1,8,Friday,Winter,westerly,0
1,2010-01-01 08:15:09,BDLONA,11,279,9,3,18,1,100101.log,2010,1,1,8,Friday,Winter,westerly,0
2,2010-01-01 08:30:01,BDLONA,11,270,10,4,17,1,100101.log,2010,1,1,8,Friday,Winter,westerly,0

============================================================
BUOY
============================================================
Shape: (140256, 15)

Columns:
['sst', 'sst_original', 'wave_height', 'wave_height_h13', 'wave_period_mean', 'wave_period_tm02', 'wave_peak_period', 'wave_max_period', 'wave_direction', 'wave_peak_direction', 'wave_angular_spread', 'sst_roll_6h', 'sst_roll_24h', 'sst_delta_3h', 'sst_delta_24h']

Dtypes:
sst                    float64
sst_original           float64
wave_height            float64
wave_height_h13        float64
wave_period_mean       float64
wave_period_tm02       float64
wave_peak_period       float64
wave_max_period        float64
wave_direction         float64
wave_peak_direction    float64
wave_angular_spread    float64
sst_roll_6h            float64
sst_roll_24h           float64
sst_delta_3h           float64
sst_delta_24h          float64
dtype: object

First rows:

,sst,sst_original,wave_height,wave_height_h13,wave_period_mean,wave_period_tm02,wave_peak_period,wave_max_period,wave_direction,wave_peak_direction,wave_angular_spread,sst_roll_6h,sst_roll_24h,sst_delta_3h,sst_delta_24h
2010-01-01 00:00:00,14.0,14.0,2.05,1.84,5.55,5.14,6.65,6.78,210.0,210.0,20.0,NaN,NaN,NaN,NaN
2010-01-01 01:00:00,14.0,14.0,1.88,1.78,5.53,5.06,7.13,7.00,213.0,205.0,20.0,NaN,NaN,NaN,NaN
2010-01-01 02:00:00,14.0,14.0,1.95,1.84,5.76,5.02,7.13,7.67,217.0,219.0,29.0,NaN,NaN,NaN,NaN

============================================================
XEMA
============================================================
Shape: (140256, 15)

Columns:
['Temperatura', 'Temperatura màxima', 'Temperatura mínima', 'Humitat relativa', 'Humitat relativa màxima', 'Humitat relativa mínima', 'Pressió atmosfèrica', 'Pressió atmosfèrica mínima', 'Velocitat del vent a 6 m (esc.)', 'Ratxa màxima del vent a 6 m', 'Precipitació', 'Precipitació màxima en 1 minut', 'Irradiància solar global', 'wind_u', 'wind_v']

Dtypes:
NOM_VARIABLE
Temperatura                        float32
Temperatura màxima                 float32
Temperatura mínima                 float32
Humitat relativa                   float32
Humitat relativa màxima            float32
Humitat relativa mínima            float32
Pressió atmosfèrica                float32
Pressió atmosfèrica mínima         float32
Velocitat del vent a 6 m (esc.)    float32
Ratxa màxima del vent a 6 m        float32
Precipitació                       float32
Precipitació màxima en 1 minut     float32
Irradiància solar global           float32
wind_u                             float32
wind_v                             float32
dtype: object

First rows:

NOM_VARIABLE,Temperatura,Temperatura màxima,Temperatura mínima,Humitat relativa,Humitat relativa màxima,Humitat relativa mínima,Pressió atmosfèrica,Pressió atmosfèrica mínima,Velocitat del vent a 6 m (esc.),Ratxa màxima del vent a 6 m,Precipitació,Precipitació màxima en 1 minut,Irradiància solar global,wind_u,wind_v
DATA_LECTURA,,,,,,,,,,,,,,,
2010-01-01 00:00:00,11.8,12.1,11.3,48.0,49.0,46.0,989.5,989.0,7.40,16.900000,0.2,0.2,0.0,-1.852812,-7.164292
2010-01-01 01:00:00,10.9,11.3,10.3,49.0,51.0,47.0,990.0,989.0,7.80,17.200001,0.0,0.0,0.0,-0.611981,-7.775955
2010-01-01 02:00:00,10.3,10.3,10.2,49.5,51.0,48.0,990.0,989.0,7.95,15.900000,0.0,0.0,0.0,-0.208105,-7.947276

In [18]:
# =========================================================
# NORMALIZE DATETIME INDEX
# =========================================================

# ---------------------------------------------------------
# WIND
# ---------------------------------------------------------

df_wind["datetime"] = pd.to_datetime(df_wind["datetime"])

df_wind = df_wind.set_index("datetime")

df_wind = df_wind.sort_index()

# ---------------------------------------------------------
# BUOY
# ---------------------------------------------------------

df_buoy.index = pd.to_datetime(df_buoy.index)

df_buoy = df_buoy.sort_index()

# ---------------------------------------------------------
# XEMA
# ---------------------------------------------------------

df_xema.index = pd.to_datetime(df_xema.index)

df_xema = df_xema.sort_index()

# Limpiar nombres extraños heredados del pivot
df_xema.index.name = "datetime"

df_xema.columns.name = None

# ---------------------------------------------------------
# VALIDATION
# ---------------------------------------------------------

print("NORMALIZATION COMPLETED")
print("-" * 50)

print("\nWIND INDEX:")
print(type(df_wind.index))
print(df_wind.index[:3])

print("\nBUOY INDEX:")
print(type(df_buoy.index))
print(df_buoy.index[:3])

print("\nXEMA INDEX:")
print(type(df_xema.index))
print(df_xema.index[:3])

NORMALIZATION COMPLETED
--------------------------------------------------

WIND INDEX:
<class 'pandas.DatetimeIndex'>
DatetimeIndex(['2010-01-01 08:00:07', '2010-01-01 08:15:09',
               '2010-01-01 08:30:01'],
              dtype='datetime64[us]', name='datetime', freq=None)

BUOY INDEX:
<class 'pandas.DatetimeIndex'>
DatetimeIndex(['2010-01-01 00:00:00', '2010-01-01 01:00:00',
               '2010-01-01 02:00:00'],
              dtype='datetime64[us]', freq=None)

XEMA INDEX:
<class 'pandas.DatetimeIndex'>
DatetimeIndex(['2010-01-01 00:00:00', '2010-01-01 01:00:00',
               '2010-01-01 02:00:00'],
              dtype='datetime64[us]', name='datetime', freq=None)

In [20]:
# =========================================================
# WIND → HOURLY RESAMPLE
# =========================================================

df_wind_hourly = (
    df_wind
    .resample("1h")
    .agg({
        "temperature": "mean",
        "wind_direction_deg": "median",
        "wind_avg": "mean",
        "wind_min": "min",
        "wind_max": "max",
        "unknown": "mean"
    })
)

print("WIND HOURLY CREATED")
print("-" * 50)

print(f"Shape: {df_wind_hourly.shape}")

print("\nFirst rows:")
display(df_wind_hourly.head(100))

print("\nMissing values:")
print(df_wind_hourly.isna().sum())

WIND HOURLY CREATED
--------------------------------------------------
Shape: (140244, 6)

First rows:

,temperature,wind_direction_deg,wind_avg,wind_min,wind_max,unknown
datetime,,,,,,
2010-01-01 08:00:00,10.750000,269.5,10.000000,3.0,22.0,1.000000
2010-01-01 09:00:00,11.000000,279.5,8.500000,1.0,21.0,0.833333
2010-01-01 10:00:00,11.285714,282.0,8.000000,2.0,20.0,0.571429
2010-01-01 11:00:00,12.000000,291.0,7.545455,1.0,22.0,0.454545
2010-01-01 12:00:00,13.000000,283.0,8.000000,1.0,23.0,0.625000
2010-01-01 13:00:00,13.000000,270.5,11.250000,3.0,23.0,1.000000
2010-01-01 14:00:00,13.000000,273.5,10.500000,3.0,25.0,1.000000
2010-01-01 15:00:00,13.000000,272.5,7.583333,1.0,24.0,0.500000
2010-01-01 16:00:00,13.000000,269.5,7.583333,1.0,20.0,0.583333
2010-01-01 17:00:00,13.000000,270.0,9.000000,2.0,22.0,0.800000
2010-01-01 18:00:00,13.000000,266.0,6.000000,1.0,13.0,0.000000
2010-01-01 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 08:00:00,10.000000,308.0,1.500000,0.0,11.0,0.000000
2010-01-02 09:00:00,9.750000,31.0,1.750000,0.0,10.0,0.000000
2010-01-02 10:00:00,10.000000,303.0,0.750000,0.0,6.0,0.000000
2010-01-02 11:00:00,10.250000,199.5,1.000000,0.0,4.0,0.000000
2010-01-02 12:00:00,11.000000,97.0,2.000000,0.0,10.0,0.000000
2010-01-02 13:00:00,11.500000,292.5,1.000000,0.0,4.0,0.000000
2010-01-02 14:00:00,12.000000,228.0,0.000000,0.0,3.0,0.000000
2010-01-02 15:00:00,12.000000,211.5,0.750000,0.0,4.0,0.000000
2010-01-02 16:00:00,12.000000,138.5,3.250000,0.0,8.0,0.000000
2010-01-02 17:00:00,12.000000,95.5,3.000000,0.0,8.0,0.000000
2010-01-02 18:00:00,12.000000,91.0,5.000000,1.0,7.0,0.000000
2010-01-02 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-02 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 08:00:00,11.000000,127.0,0.000000,0.0,0.0,0.000000
2010-01-03 09:00:00,11.000000,127.0,0.000000,0.0,0.0,0.000000
2010-01-03 10:00:00,11.000000,127.0,0.000000,0.0,0.0,0.000000
2010-01-03 11:00:00,11.750000,127.0,0.000000,0.0,0.0,0.000000
2010-01-03 12:00:00,11.750000,127.0,0.000000,0.0,0.0,0.000000
2010-01-03 13:00:00,12.000000,236.0,1.250000,0.0,6.0,0.000000
2010-01-03 14:00:00,12.500000,241.5,2.750000,0.0,8.0,0.000000
2010-01-03 15:00:00,12.500000,202.0,6.000000,3.0,8.0,0.000000
2010-01-03 16:00:00,12.500000,183.0,0.750000,0.0,5.0,0.000000
2010-01-03 17:00:00,12.500000,183.0,0.000000,0.0,0.0,0.000000
2010-01-03 18:00:00,13.000000,183.0,0.000000,0.0,0.0,0.000000
2010-01-03 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-03 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 08:00:00,11.000000,61.0,2.000000,0.0,7.0,0.000000
2010-01-04 09:00:00,10.500000,16.0,1.500000,0.0,6.0,0.000000
2010-01-04 10:00:00,10.750000,32.5,2.500000,0.0,5.0,0.000000
2010-01-04 11:00:00,11.000000,76.0,5.500000,0.0,9.0,0.166667
2010-01-04 12:00:00,11.000000,79.5,7.250000,4.0,11.0,0.375000
2010-01-04 13:00:00,11.000000,73.0,6.500000,4.0,10.0,0.000000
2010-01-04 14:00:00,11.500000,62.0,2.500000,0.0,8.0,0.000000
2010-01-04 15:00:00,11.750000,55.0,0.000000,0.0,0.0,0.000000
2010-01-04 16:00:00,11.250000,55.0,0.000000,0.0,0.0,0.000000
2010-01-04 17:00:00,11.250000,55.0,0.000000,0.0,0.0,0.000000
2010-01-04 18:00:00,11.000000,55.0,0.000000,0.0,0.0,0.000000
2010-01-04 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05 08:00:00,11.500000,55.0,0.000000,0.0,0.0,0.000000
2010-01-05 09:00:00,12.000000,55.0,0.000000,0.0,0.0,0.000000
2010-01-05 10:00:00,11.750000,55.0,0.000000,0.0,0.0,0.000000
2010-01-05 11:00:00,12.000000,55.0,0.000000,0.0,0.0,0.000000

Missing values:
temperature           67297
wind_direction_deg    67297
wind_avg              67297
wind_min              67297
wind_max              67297
unknown               67297
dtype: int64

In [21]:
# =========================================================
# ANALYZE TEMPORAL GAPS
# =========================================================

wind_diffs = (
    df_wind.index
    .to_series()
    .diff()
)

print("TEMPORAL GAPS ANALYSIS")
print("-" * 50)

print("\nMost common gaps:")
print(
    wind_diffs.value_counts()
    .head(20)
)

print("\nLargest gaps:")
print(
    wind_diffs
    .sort_values(ascending=False)
    .head(20)
)

TEMPORAL GAPS ANALYSIS
--------------------------------------------------

Most common gaps:
datetime
0 days 00:15:00    56976
0 days 00:15:02    47631
0 days 00:15:01    43840
0 days 00:15:03    16627
0 days 00:14:52    11638
0 days 00:15:04    10451
0 days 00:14:55     7877
0 days 00:14:56     7130
0 days 00:15:05     6982
0 days 00:01:00     6937
0 days 00:14:54     6510
0 days 00:14:53     6081
0 days 00:14:51     5818
0 days 00:14:57     5265
0 days 00:14:59     5193
0 days 00:15:06     4375
0 days 00:14:58     4278
0 days 00:15:07     2888
0 days 00:02:00     2025
0 days 00:01:01     1724
Name: count, dtype: int64

Largest gaps:
datetime
2013-12-05 08:00:02   97 days 11:59:56
2023-05-26 07:00:03   25 days 10:00:02
2019-02-07 12:45:07    6 days 18:45:06
2014-09-05 13:00:08    2 days 21:45:07
2011-11-05 12:30:01    2 days 19:14:56
2019-02-09 13:00:08    2 days 00:15:01
2021-10-18 18:15:06    1 days 23:00:05
2010-01-11 13:30:07    1 days 22:45:06
2023-02-14 12:00:06    1 days 19:00:01
2019-04-10 12:00:10    1 days 18:15:07
2018-09-07 13:30:09    1 days 17:30:06
2011-06-09 11:45:04    1 days 15:45:04
2025-06-01 12:45:05    1 days 15:45:01
2012-05-02 09:00:04    1 days 15:14:57
2014-07-19 08:00:10    1 days 14:30:03
2020-08-04 07:00:08    1 days 10:00:00
2020-07-30 07:00:04    1 days 09:59:55
2012-05-07 11:30:00    1 days 02:44:52
2011-06-07 12:15:00    1 days 00:44:52
2019-04-11 11:45:08    0 days 23:44:58
Name: datetime, dtype: timedelta64[us]

In [22]:
# =========================================================
# CREATE ATMOSPHERIC BASE DATASET
# =========================================================

df_base = df_xema.join(
    df_buoy,
    how="inner"
)

print("BASE DATASET CREATED")
print("-" * 50)

print(f"Shape: {df_base.shape}")

print("\nDatetime range:")
print(df_base.index.min())
print(df_base.index.max())

print("\nMissing values:")
print(
    df_base.isna().sum().sort_values(ascending=False).head(10)
)

print("\nFirst rows:")
display(df_base.head())

BASE DATASET CREATED
--------------------------------------------------
Shape: (140256, 30)

Datetime range:
2010-01-01 00:00:00
2025-12-31 23:00:00

Missing values:
wave_angular_spread    11527
wave_peak_direction    11527
wave_max_period        10770
wave_direction          4643
wave_period_tm02        4156
wave_peak_period        3886
wave_period_mean        3886
wave_height_h13         3886
wave_height             3886
sst_original            3596
dtype: int64

First rows:

,Temperatura,Temperatura màxima,Temperatura mínima,Humitat relativa,Humitat relativa màxima,Humitat relativa mínima,Pressió atmosfèrica,Pressió atmosfèrica mínima,Velocitat del vent a 6 m (esc.),Ratxa màxima del vent a 6 m,Precipitació,Precipitació màxima en 1 minut,Irradiància solar global,wind_u,wind_v,sst,sst_original,wave_height,wave_height_h13,wave_period_mean,wave_period_tm02,wave_peak_period,wave_max_period,wave_direction,wave_peak_direction,wave_angular_spread,sst_roll_6h,sst_roll_24h,sst_delta_3h,sst_delta_24h
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2010-01-01 00:00:00,11.80,12.1,11.3,48.0,49.0,46.0,989.5,989.0,7.40,16.900000,0.2,0.2,0.0,-1.852812,-7.164292,14.0,14.0,2.05,1.84,5.55,5.14,6.65,6.78,210.0,210.0,20.0,NaN,NaN,NaN,NaN
2010-01-01 01:00:00,10.90,11.3,10.3,49.0,51.0,47.0,990.0,989.0,7.80,17.200001,0.0,0.0,0.0,-0.611981,-7.775955,14.0,14.0,1.88,1.78,5.53,5.06,7.13,7.00,213.0,205.0,20.0,NaN,NaN,NaN,NaN
2010-01-01 02:00:00,10.30,10.3,10.2,49.5,51.0,48.0,990.0,989.0,7.95,15.900000,0.0,0.0,0.0,-0.208105,-7.947276,14.0,14.0,1.95,1.84,5.76,5.02,7.13,7.67,217.0,219.0,29.0,NaN,NaN,NaN,NaN
2010-01-01 03:00:00,9.85,10.2,9.6,47.0,48.0,47.0,990.5,990.0,8.00,16.299999,0.0,0.0,0.0,-0.627673,-7.975338,14.0,14.0,2.24,2.08,6.10,5.53,7.68,8.55,214.0,213.0,24.0,NaN,NaN,0.0,NaN
2010-01-01 04:00:00,9.50,9.6,9.4,46.0,47.0,45.0,991.0,990.0,7.15,15.900000,0.0,0.0,0.0,-1.241584,-7.041375,14.0,14.0,2.62,2.37,6.46,5.85,7.67,8.19,214.0,212.0,23.0,NaN,NaN,0.0,NaN

In [23]:
# =========================================================
# MERGE WIND DATA
# =========================================================

df_master = df_base.join(
    df_wind_hourly,
    how="left"
)

print("MASTER DATASET CREATED")
print("-" * 50)

print(f"Shape: {df_master.shape}")

print("\nDatetime range:")
print(df_master.index.min())
print(df_master.index.max())

print("\nWIND missing values:")
print(
    df_master[
        [
            "temperature",
            "wind_avg",
            "wind_max"
        ]
    ]
    .isna()
    .sum()
)

print("\nFirst rows:")
display(df_master.head())

MASTER DATASET CREATED
--------------------------------------------------
Shape: (140256, 36)

Datetime range:
2010-01-01 00:00:00
2025-12-31 23:00:00

WIND missing values:
temperature    67309
wind_avg       67309
wind_max       67309
dtype: int64

First rows:

,Temperatura,Temperatura màxima,Temperatura mínima,Humitat relativa,Humitat relativa màxima,Humitat relativa mínima,Pressió atmosfèrica,Pressió atmosfèrica mínima,Velocitat del vent a 6 m (esc.),Ratxa màxima del vent a 6 m,Precipitació,Precipitació màxima en 1 minut,Irradiància solar global,wind_u,wind_v,sst,sst_original,wave_height,wave_height_h13,wave_period_mean,wave_period_tm02,wave_peak_period,wave_max_period,wave_direction,wave_peak_direction,wave_angular_spread,sst_roll_6h,sst_roll_24h,sst_delta_3h,sst_delta_24h,temperature,wind_direction_deg,wind_avg,wind_min,wind_max,unknown
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2010-01-01 00:00:00,11.80,12.1,11.3,48.0,49.0,46.0,989.5,989.0,7.40,16.900000,0.2,0.2,0.0,-1.852812,-7.164292,14.0,14.0,2.05,1.84,5.55,5.14,6.65,6.78,210.0,210.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 01:00:00,10.90,11.3,10.3,49.0,51.0,47.0,990.0,989.0,7.80,17.200001,0.0,0.0,0.0,-0.611981,-7.775955,14.0,14.0,1.88,1.78,5.53,5.06,7.13,7.00,213.0,205.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 02:00:00,10.30,10.3,10.2,49.5,51.0,48.0,990.0,989.0,7.95,15.900000,0.0,0.0,0.0,-0.208105,-7.947276,14.0,14.0,1.95,1.84,5.76,5.02,7.13,7.67,217.0,219.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 03:00:00,9.85,10.2,9.6,47.0,48.0,47.0,990.5,990.0,8.00,16.299999,0.0,0.0,0.0,-0.627673,-7.975338,14.0,14.0,2.24,2.08,6.10,5.53,7.68,8.55,214.0,213.0,24.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01 04:00:00,9.50,9.6,9.4,46.0,47.0,45.0,991.0,990.0,7.15,15.900000,0.0,0.0,0.0,-1.241584,-7.041375,14.0,14.0,2.62,2.37,6.46,5.85,7.67,8.19,214.0,212.0,23.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# =========================================================
# INFER OPERATIONAL HOURS FROM DATA
# =========================================================

# ---------------------------------------------------------
# Hours where wind observations exist
# ---------------------------------------------------------

wind_hours = (
    df_master[df_master["wind_avg"].notna()]
    .copy()
)

wind_hours["month"] = wind_hours.index.month
wind_hours["hour"] = wind_hours.index.hour

# ---------------------------------------------------------
# First and last active hour by month
# ---------------------------------------------------------

operational_hours = (
    wind_hours
    .groupby("month")["hour"]
    .agg(["min", "max"])
)

print("INFERRED OPERATIONAL HOURS")
print("-" * 50)

display(operational_hours)

INFERRED OPERATIONAL HOURS
--------------------------------------------------

       min  max
month
1        7   19
2        7   19
3        7   21
4        7   21
5        7   21
6        7   21
7        7   21
8        7   21
9        7   21
10       7   21
11       7   19
12       7   19

In [25]:
# =========================================================
# CREATE DYNAMIC OPERATIONAL WINDOW
# =========================================================

# ---------------------------------------------------------
# Month → operational hours dictionaries
# ---------------------------------------------------------

month_start_hour = operational_hours["min"].to_dict()
month_end_hour = operational_hours["max"].to_dict()

# ---------------------------------------------------------
# Extract temporal features
# ---------------------------------------------------------

df_master["month"] = df_master.index.month
df_master["hour"] = df_master.index.hour

# ---------------------------------------------------------
# Dynamic operational flag
# ---------------------------------------------------------

df_master["is_operational_hour"] = df_master.apply(
    lambda row:
        (
            month_start_hour[row["month"]]
            <= row["hour"]
            <= month_end_hour[row["month"]]
        ),
    axis=1
).astype("int8")

# ---------------------------------------------------------
# Wind data available
# ---------------------------------------------------------

df_master["wind_data_available"] = (
    df_master["wind_avg"]
    .notna()
    .astype("int8")
)

# ---------------------------------------------------------
# Valid wind observation
# ---------------------------------------------------------

df_master["valid_wind_observation"] = (
    (
        df_master["wind_data_available"] == 1
    ) &
    (
        df_master["is_operational_hour"] == 1
    )
).astype("int8")

# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("DYNAMIC OPERATIONAL FEATURES CREATED")
print("-" * 50)

print("\nOperational hour distribution:")
print(
    df_master["is_operational_hour"]
    .value_counts()
)

print("\nValid observations:")
print(
    df_master["valid_wind_observation"]
    .value_counts()
)

display(
    df_master[
        [
            "wind_avg",
            "wind_data_available",
            "is_operational_hour",
            "valid_wind_observation"
        ]
    ].head(48)
)

DYNAMIC OPERATIONAL FEATURES CREATED
--------------------------------------------------

Operational hour distribution:
is_operational_hour
1    83812
0    56444
Name: count, dtype: int64

Valid observations:
valid_wind_observation
1    72947
0    67309
Name: count, dtype: int64

,wind_avg,wind_data_available,is_operational_hour,valid_wind_observation
datetime,,,,
2010-01-01 00:00:00,NaN,0,0,0
2010-01-01 01:00:00,NaN,0,0,0
2010-01-01 02:00:00,NaN,0,0,0
2010-01-01 03:00:00,NaN,0,0,0
2010-01-01 04:00:00,NaN,0,0,0
2010-01-01 05:00:00,NaN,0,0,0
2010-01-01 06:00:00,NaN,0,0,0
2010-01-01 07:00:00,NaN,0,1,0
2010-01-01 08:00:00,10.000000,1,1,1
2010-01-01 09:00:00,8.500000,1,1,1
2010-01-01 10:00:00,8.000000,1,1,1
2010-01-01 11:00:00,7.545455,1,1,1
2010-01-01 12:00:00,8.000000,1,1,1
2010-01-01 13:00:00,11.250000,1,1,1
2010-01-01 14:00:00,10.500000,1,1,1
2010-01-01 15:00:00,7.583333,1,1,1
2010-01-01 16:00:00,7.583333,1,1,1
2010-01-01 17:00:00,9.000000,1,1,1
2010-01-01 18:00:00,6.000000,1,1,1
2010-01-01 19:00:00,NaN,0,1,0
2010-01-01 20:00:00,NaN,0,0,0
2010-01-01 21:00:00,NaN,0,0,0
2010-01-01 22:00:00,NaN,0,0,0
2010-01-01 23:00:00,NaN,0,0,0
2010-01-02 00:00:00,NaN,0,0,0
2010-01-02 01:00:00,NaN,0,0,0
2010-01-02 02:00:00,NaN,0,0,0
2010-01-02 03:00:00,NaN,0,0,0
2010-01-02 04:00:00,NaN,0,0,0
2010-01-02 05:00:00,NaN,0,0,0
2010-01-02 06:00:00,NaN,0,0,0
2010-01-02 07:00:00,NaN,0,1,0
2010-01-02 08:00:00,1.500000,1,1,1
2010-01-02 09:00:00,1.750000,1,1,1
2010-01-02 10:00:00,0.750000,1,1,1
2010-01-02 11:00:00,1.000000,1,1,1
2010-01-02 12:00:00,2.000000,1,1,1
2010-01-02 13:00:00,1.000000,1,1,1
2010-01-02 14:00:00,0.000000,1,1,1
2010-01-02 15:00:00,0.750000,1,1,1
2010-01-02 16:00:00,3.250000,1,1,1
2010-01-02 17:00:00,3.000000,1,1,1
2010-01-02 18:00:00,5.000000,1,1,1
2010-01-02 19:00:00,NaN,0,1,0
2010-01-02 20:00:00,NaN,0,0,0
2010-01-02 21:00:00,NaN,0,0,0
2010-01-02 22:00:00,NaN,0,0,0
2010-01-02 23:00:00,NaN,0,0,0

In [26]:
# =========================================================
# CREATE OPERATIONAL GAP FEATURE
# =========================================================

df_master["operational_gap"] = (
    (
        df_master["is_operational_hour"] == 1
    ) &
    (
        df_master["wind_data_available"] == 0
    )
).astype("int8")

print("OPERATIONAL GAP FEATURE CREATED")
print("-" * 50)

print(
    df_master["operational_gap"]
    .value_counts()
)

print("\nGap percentage:")

gap_pct = (
    df_master["operational_gap"]
    .mean() * 100
)

print(f"{gap_pct:.2f}%")

OPERATIONAL GAP FEATURE CREATED
--------------------------------------------------
operational_gap
0    129391
1     10865
Name: count, dtype: int64

Gap percentage:
7.75%

In [27]:
# =========================================================
# EXPORT MASTER DATASET
# =========================================================

OUTPUT_PATH = "../data/gold/master_hourly_dataset.parquet"

df_master.to_parquet(
    OUTPUT_PATH
)

print("MASTER DATASET EXPORTED")
print("-" * 50)

print(f"Path: {OUTPUT_PATH}")

print(f"\nShape: {df_master.shape}")

print("\nDatetime range:")
print(df_master.index.min())
print(df_master.index.max())

print("\nTotal columns:")
print(len(df_master.columns))

print("\nColumns:")
print(df_master.columns.tolist())

MASTER DATASET EXPORTED
--------------------------------------------------
Path: ../data/gold/master_hourly_dataset.parquet

Shape: (140256, 42)

Datetime range:
2010-01-01 00:00:00
2025-12-31 23:00:00

Total columns:
42

Columns:
['Temperatura', 'Temperatura màxima', 'Temperatura mínima', 'Humitat relativa', 'Humitat relativa màxima', 'Humitat relativa mínima', 'Pressió atmosfèrica', 'Pressió atmosfèrica mínima', 'Velocitat del vent a 6 m (esc.)', 'Ratxa màxima del vent a 6 m', 'Precipitació', 'Precipitació màxima en 1 minut', 'Irradiància solar global', 'wind_u', 'wind_v', 'sst', 'sst_original', 'wave_height', 'wave_height_h13', 'wave_period_mean', 'wave_period_tm02', 'wave_peak_period', 'wave_max_period', 'wave_direction', 'wave_peak_direction', 'wave_angular_spread', 'sst_roll_6h', 'sst_roll_24h', 'sst_delta_3h', 'sst_delta_24h', 'temperature', 'wind_direction_deg', 'wind_avg', 'wind_min', 'wind_max', 'unknown', 'month', 'hour', 'is_operational_hour', 'wind_data_available', 'valid_wind_observation', 'operational_gap']